version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:2.392
    container_name: jenkins
    user: root
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins-logs:/var/log/jenkins
      - ./src:/var/jenkins_home/src
    restart: unless-stopped
    networks:
      - net

networks:
 net:
    ipam:
     driver: default
     config:
      - subnet: "10.10.0.0/16"
