pipeline {
    agent {
        label 'assignment-agent'
    }
    
    stages {
        stage('Build') {
            steps {
                sh 'python3 ./src/main.py'
            }
        }
    }
}
